export default {
  "/": [
    { text: "介绍", link: "/" },
    { text: "快速上手", link: "/quickstart/" },
    { text: "场景系统", link: "/scene-system/" },
    { text: "2D 图形", link: "/2D-graphics/" },
    { text: "3D 图形", link: "/3D-graphics/" },
    { text: "GDScript 脚本", link: "/gdscript/" },
    { text: "用户输入", link: "/input-handling/" },
    { text: "用户界面", link: "/ui/" },
    { text: "物理引擎", link: "/physic-system/" },
    { text: "文件系统", link: "/file/" },
    { text: "声音", link: "/audio/" },
    { text: "动画", link: "/animation/" },
    { text: "粒子效果", link: "/particle/" },
    { text: "光照与阴影", link: "/light/" },
    // { text: "插件", link: "/plugins/" },
    { text: "项目设置", link: "/configs/" },
    { text: "导出", link: "/export/" },
  ],
  "/guide/": [],
};
