#!/usr/bin/env sh
# . "$(dirname -- "$0")/_/husky.sh"

# 确保脚本抛出遇到的错误
set -e
# 生成静态文件

npm run build

# 进入生成的文件夹
cd "./docs/.vuepress/dist"

git init
git add .
git commit --no-verify -m 'deploy'

# 如果发布到 origin gh-pages
# git branch -m master gh-pages # 匹配路径

# 如果 token 过期了，需要修改当前 origin => `git remote -v && git remote add origin url`
git remote add origin "git@github.com:Da222Da/godot.git"
git push -f -u origin master:gh-pages


cd "../"
rm -rf "./dist"
